# Generated by Django 4.0.1 on 2022-01-31 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('guest_number', models.DecimalField(decimal_places=0, max_digits=4, verbose_name='Количество гостей')),
                ('phone_number', models.DecimalField(decimal_places=0, max_digits=11, verbose_name='Номер телефона')),
                ('datetime', models.DateTimeField(verbose_name='Время желаемого бронирования')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Пожелания')),
                ('status', models.BooleanField(default=False, verbose_name='Статус заявки')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.DecimalField(decimal_places=0, max_digits=4, unique=True, verbose_name='Номер стола')),
                ('seats', models.DecimalField(decimal_places=0, max_digits=4, verbose_name='Количество мест')),
            ],
            options={
                'verbose_name': 'Стол',
                'verbose_name_plural': 'Столы',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата бронирования')),
                ('beginning_time', models.DateTimeField(verbose_name='Время начала бронирования')),
                ('ending_time', models.DateTimeField(verbose_name='Время конца бронирования')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest', to='table_book.queue')),
                ('table_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table', to='table_book.tables')),
            ],
            options={
                'verbose_name': 'Бронь',
                'verbose_name_plural': 'Брони',
            },
        ),
    ]
