# Generated by Django 4.0.1 on 2022-06-23 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('datetime', models.DateTimeField(verbose_name='Дата и время')),
                ('guest_number', models.IntegerField(verbose_name='Количество гостей')),
                ('phone_number', models.DecimalField(decimal_places=0, max_digits=11, verbose_name='Номер телефона')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Примечание')),
                ('status', models.BooleanField(default=False, verbose_name='Статус заявки')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='Номер стола')),
                ('seats', models.IntegerField(verbose_name='Количество мест')),
                ('status', models.BooleanField(default=True, verbose_name='Свободен')),
            ],
            options={
                'verbose_name': 'Стол',
                'verbose_name_plural': 'Столы',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='table_book.application')),
                ('table_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table', to='table_book.tables')),
            ],
            options={
                'verbose_name': 'Бронь',
                'verbose_name_plural': 'Брони',
            },
        ),
    ]
