# Generated by Django 4.0.1 on 2022-01-31 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table_book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='date',
        ),
    ]
